### ISSUE TITLE
xxd is problematic

### ISSUE THREAD

**Issue by mxmilkiib** [jpcima/ssr#1]
vim provided xxd but [not](https://aur.archlinux.org/packages/ssr.lv2-git/#comment-774442) all folks have or want vim and xxd-standalone conflicts with vim

could the use of xxd be avoided?

**Comment by jpcima** [comment]
Hi, I replaced this with more "unix" commands at c5987e3cf3a31d22f448cb163d3dca3d8d884c66
does this help?

**Comment by mxmilkiib** [comment]
Yes, thanks :)
